### PR TITLE
Update GET_YOUR_SESSION_ID.md

### PR DESCRIPTION
**Pull request by JackAttack365**
Adds more detail and browser specific content, and updates the alternate method

### CODE REVIEW

**Comment by TheCommCraft** [comment]
The cookie is named scratchsessionsid

**Comment by TheCommCraft** [comment]
And what is .DS_STORE used for?

**Comment by JackAttack365** [comment]
> The cookie is named scratchsessionsid

I can't find where I said something different

**Comment by TheCommCraft** [comment]
Row 8

**Comment by JackAttack365** [comment]
Cleaner PR: https://github.com/TimMcCool/scratchattach/pull/221

**Pull request closed without merging**
