### PR TITLE
Merge v2 into main branch

### PR DESCRIPTION
**Pull request by TimMcCool**

### CODE REVIEW

**Comment by TheCommCraft** [comment]
y

Tim ***@***.***> schrieb am Sa., 12. Okt. 2024, 13:54:

**Comment by TimMcCool** [comment]
because v2 is finished

**Comment by TheCommCraft** [comment]
Have you changed the Docs yet?

Tim ***@***.***> schrieb am Sa., 12. Okt. 2024, 13:56:

**Comment by TimMcCool** [comment]
no, I'm still working on that rn. The code for v2 is merged into the main branch, but there's no automated PyPi upload so on PyPi there's still the old version atm

**Pull request merged**
