### PR TITLE
filterbot bugfix and classes

### PR DESCRIPTION
**Pull request by TheCommCraft**
Note the addition of `__init__.py` file and the need to put something in them

### CODE REVIEW

**Review by TimMcCool — COMMENTED** [review]
What advantages come from this change? Imo it creates an unnecessarily excessive amount of classes

**Comment by TimMcCool** [comment]
I'll merge the session string update

**Comment by TimMcCool** [comment]
Adding __init__.py files to sub-folders is actually not necessary afaik because everything is imported in the top-level __init__.py files. I tested it by replacing the files in the site-packages/scratchattach folder and it works.

I'm not that experienced with Python library development tho, so maybe there are good reasons to add __init__.py files to every sub-folder that I don't know about (if so, please tell me)

**Comment by TimMcCool** [comment]
Ok ig adding the __init__.py files is necessary because it allows users to import stuff that isn't imported in the top-level __init__.py file. I'll add them

**Comment by TheCommCraft** [comment]
First, there were some bugs in the code that can be fixed this way and secondly, it allows users to create their own filters.

**Comment by TheCommCraft** [comment]
One of the commits fix a bug that prevents you from adding Spam-Filters or SoftFilters

**Comment by TimMcCool** [comment]
Oh ok. Fixed the bug that prevented users from adding SpamFilters and SoftFilters. But adding own filters is already possible by creating a class that inherits from HardFilter / SoftFilter / SpamFilter and overriding the apply method

**Comment by TheCommCraft** [comment]
ok

**Pull request closed without merging**
