### PR TITLE
Allow searching 1K+ studios/projects

### PR DESCRIPTION
**Pull request by LIZARD-OFFICIAL**
Right now, if you try to search more than 40 projects/studios, it won't work.
I fixed it by using offset.

### CODE REVIEW

**Review by namtacs — APPROVED** [review]
I suggest merging. It will be much easier to work with these methods.
Very scuffed code tho. Makes too much excess requests and bad variable naming.
Working on a pr to this pr to fix that.

**Comment by ninjamar** [comment]
You should consider wrapping these changes in a function, since they deal with lots of common code

**Review by BuStudios — APPROVED** [review]
This seems quite useful. I would also suggest merging

**Comment by namtacs** [comment]
Made a better PR (#206). Fixes bugs, follows a common template for simple requests and clear code.

**Comment by LIZARD-OFFICIAL** [comment]
#206 is much better than what I made, merge that one instead when its finished, cuz its more space efficient.

**Pull request closed without merging**
