### PR TITLE
Add CI action to format code on push or PR

### PR DESCRIPTION
**Pull request by lemystic**
This would take other developers' poorly formatted Python code and format it to make it consistent with the entire codebase. [Black](https://black.readthedocs.io/) formats your general code and [Isort](https://isort.readthedocs.io/) structures imports to match proper style guides. 

Just remember to add a GitHub token to your repository secrets by going to [token settings](https://github.com/settings/tokens) and creating a classic token that you can copy and paste into a new secret.

Hopefully, this helps :) (sorry for 10 commits I had to do everything in the browser)

### CODE REVIEW

**Comment by lemystic** [comment]
Bump, any chance to review?

**Comment by lemystic** [comment]
@TimMcCool bump

**Comment by TimMcCool** [comment]
Will maybe be added

**Comment by TimMcCool** [comment]
Will be implemented in v1.1.8

**Comment by TimMcCool** [comment]
Will not be implemented

**Pull request closed without merging**
