### PR TITLE
Added (smart) translation + TTS api

### PR DESCRIPTION
**Pull request by FAReTek1**
Used the scratch translation api to make a function in other_apis.py

Also added a supported languages list/dict in the utils folder
This uses the api at https://translate-service.scratch.mit.edu/translate?language={language}&text={text}

---

Also added a tts api in the same file using:
https://synthesis-service.scratch.mit.edu/synth?locale={language}&gender={gender[0]}&text={text}
Added relevant languages for tts to the languages file in the utils folder asw

### CODE REVIEW

**Comment by FAReTek1** [comment]
true actually. but it will be little annoying to make a list of keys and values

**Comment by FAReTek1** [comment]
> I recommend using an Enum for the languages

I'll try to make an enum and then make functions/methods to get the data from those enums

**Comment by TheCommCraft** [comment]
Are you aware of what an Enum is?

faretek ***@***.***> schrieb am Mi., 13. Nov. 2024, 18:56:

**Comment by TheCommCraft** [comment]
In case you aren't, I suggest reading the documentation at
https://docs.python.org/3/library/enum

Simon Gilde ***@***.***> schrieb am Mi., 13. Nov. 2024, 18:59:

**Comment by FAReTek1** [comment]
yesnt. i kind of addex one but its not very helpful for this use case

having to use .value is also a bit annoying

**Comment by TheCommCraft** [comment]
You supply an enum as the argument and take the value from the enum in the function is what you should do

**Comment by TheCommCraft** [comment]
You supply an enum as the argument and take the value from the enum in the function is what you should do

**Comment by TheCommCraft** [comment]
You should make the function take an instance of the Enum and take the value out of it in the function

**Comment by TheCommCraft** [comment]
That's what Enums are used for

**Comment by FAReTek1** [comment]
i added an enum (afaik its an enum) but I s not helpful for searching the list of languages. i might abstract the code a bit (making a language class) to clean it up a bit

**Comment by TheCommCraft** [comment]
If you use a good IDE (e.g.vs code), the Enum should help you write code
with the Languages

faretek ***@***.***> schrieb am Sa., 16. Nov. 2024, 10:01:

**Comment by FAReTek1** [comment]
image
does this count as an enum??

**Comment by FAReTek1** [comment]
the problem is is what i really want is a list of keys and values, and those are easier to do with dictionaries

**Comment by FAReTek1** [comment]
ill make a languages class to abstract teh stuff a bit actually

**Comment by FAReTek1** [comment]
there:
langs = [Language('Albanian', 'sq'),
         Language('Amharic', 'am'),
         Language('Arabic', 'ar', ['ar'], 'arb', True),
         Language('Armenian', 'hy'),
         Language('Azerbaijani', 'az'),
         Language('Basque', 'eu'),
         Language('Belarusian', 'be'),
         Language('Bulgarian', 'bg'),
         Language('Catalan', 'ca'),
         Language('Chinese (Traditional)', 'zh-tw'),
         Language('Croatian', 'hr'),
         Language('Czech', 'cs'),
         Language('Danish', 'da', ['da'], 'da-DK', False),
         Language('Dutch', 'nl', ['nl'], 'nl-NL', False),
         Language('English', 'en', ['en'], 'en-US', False),
         Language('Esperanto', 'eo'),
         Language('Estonian', 'et'),
         Language('Finnish', 'fi'),
         Language('French', 'fr', ['fr'], 'fr-FR', False),
         Language('Galician', 'gl'),
         Language('German', 'de', ['de'], 'de-DE', False),
         Language('Greek', 'el'),
         Language('Haitian Creole', 'ht'),
         Language('Hindi', 'hi', ['hi'], 'hi-IN', True),
         Language('Hungarian', 'hu'),
         Language('Icelandic', 'is', ['is'], 'is-IS', False),
         Language('Indonesian', 'id'),
         Language('Irish', 'ga'),
         Language('Italian', 'it', ['it'], 'it-IT', False),
         Language('Japanese', 'ja', ['ja', 'ja-hira'], 'ja-JP', False),
         Language('Kannada', 'kn'),
         Language('Korean', 'ko', ['ko'], 'ko-KR', True),
         Language('Kurdish (Kurmanji)', 'ku'),
         Language('Latin', 'la'),
         Language('Latvian', 'lv'),
         Language('Lithuanian', 'lt'),
         Language('Macedonian', 'mk'),
         Language('Malay', 'ms'),
         Language('Malayalam', 'ml'),
         Language('Maltese', 'mt'),
         Language('Maori', 'mi'),
         Language('Marathi', 'mr'),
         Language('Mongolian', 'mn'),
         Language('Myanmar (Burmese)', 'my'),
         Language('Persian', 'fa'),
         Language('Polish', 'pl', ['pl'], 'pl-PL', False),
         Language('Portuguese', 'pt'),
         Language('Romanian', 'ro', ['ro'], 'ro-RO', True),
         Language('Russian', 'ru', ['ru'], 'ru-RU', False),
         Language('Scots Gaelic', 'gd'),
         Language('Serbian', 'sr'),
         Language('Slovak', 'sk'),
         Language('Slovenian', 'sl'),
         Language('Spanish', 'es'),
         Language('Swedish', 'sv', ['sv'], 'sv-SE', True),
         Language('Telugu', 'te'),
         Language('Thai', 'th'),
         Language('Turkish', 'tr', ['tr'], 'tr-TR', True),
         Language('Ukrainian', 'uk'),
         Language('Uzbek', 'uz'),
         Language('Vietnamese', 'vi'),
         Language('Welsh', 'cy', ['cy'], 'cy-GB', True),
         Language('Zulu', 'zu'),
         Language('Hebrew', 'he'),
         Language('Chinese (Simplified)', 'zh-cn'),
         Language(None, None, ['zh-cn', 'zh-tw'], 'cmn-CN', True),
         Language(None, None, ['nb', 'nn'], 'nb-NO', True),
         Language(None, None, ['pt-br'], 'pt-BR', False),
         Language(None, None, ['pt'], 'pt-PT', False),
         Language(None, None, ['es'], 'es-ES', False),
         Language(None, None, ['es-419'], 'es-US', False)]

**Comment by FAReTek1** [comment]
hmm. an enum would be nice tho for code completion

**Comment by FAReTek1** [comment]
easy to add

**Comment by FAReTek1** [comment]
image
is this good then

**Comment by FAReTek1** [comment]
do i have to inherit from enum? It feels like it would work nicer without it since then you don't need to do .value all the time

**Comment by FAReTek1** [comment]
oh, i just don't know enums well enough. there is actually an implementation for using for loops with it already

**Comment by FAReTek1** [comment]
image
yeah this find function should do the job

**Comment by FAReTek1** [comment]
now i will use these for tts and translate

**Comment by FAReTek1** [comment]
ok hopefully the new commit means its all good

**Comment by FAReTek1** [comment]
if this gets merged, I'll have to update the scratchblocks part of scralenium since that also has language data

**Comment by TheCommCraft** [comment]
You just need to do .value in the functions that use the enum instances

**Review by TheCommCraft — CHANGES_REQUESTED** [review]
Possibly change lines 152-156 to
```
if isinstance(language, str):
        if language.lower() in Languages.all_of("code", str.lower):
            lang = Languages.find(language.lower(), "code")
        elif language.lower() in Languages.all_of("name", str.lower):
            lang = Languages.find(language.lower(), apply_func=str.lower)
    elif isinstance(language, Languages):
        lang = language
```

**Comment by TheCommCraft** [comment]
The _Language class could also be a dataclass

**Comment by FAReTek1** [comment]
ok

**Comment by FAReTek1** [comment]
ill take a look tmrw

**Comment by FAReTek1** [comment]
yes, i'm making a few changes to your addition but it works now with any of these settings:
```py
import scratchattach as sa

print(sa.translate("hungarian", "radish"))
print(sa.translate(sa.Languages.Hungarian, "radish"))
print(sa.translate(sa.Languages.Hungarian.value, "radish"))
print(sa.translate("hu", "radish"))

```

**Comment by FAReTek1** [comment]
i will take a look at the dataclass stuff now

**Comment by FAReTek1** [comment]
dang, wow dataclasses makes the code a lot more compact, thanks for telling me about that

**Comment by FAReTek1** [comment]
its basically just a python struct

**Comment by FAReTek1** [comment]
> Possibly change lines 152-156 to
> 
> ```
> if isinstance(language, str):
>         if language.lower() in Languages.all_of("code", str.lower):
>             lang = Languages.find(language.lower(), "code")
>         elif language.lower() in Languages.all_of("name", str.lower):
>             lang = Languages.find(language.lower(), apply_func=str.lower)
>     elif isinstance(language, Languages):
>         lang = language
> ```

i added that now but im not sure how i tell github that i did

**Review by TheCommCraft — APPROVED** [review]
Seems good now

**Comment by FAReTek1** [comment]
the cmn_CN's attributes should be added to chinese_simplified and chinese_traditional since it is just the tts version of Chinese which applies to both simplified and traditional
likewise, pt_pt could be merged with Portuguese and es_es with Spanish

**Comment by FAReTek1** [comment]
added now

**Comment by FAReTek1** [comment]
also should probably add better error handling - maybe even add more to exceptions.py

**Comment by FAReTek1** [comment]
maybe i should make an enum for supported tts genders

**Comment by FAReTek1** [comment]
maybe change supportedlangs file into utils.enums or something

**Comment by FAReTek1** [comment]
so instead of making a new file for each enum, just put those kinds of things there

**Comment by FAReTek1** [comment]
ill turn those extra functions (find and all_of) into something that comes under an enumwrapper class

**Comment by TheCommCraft** [comment]
Are you done with the pull request?

**Comment by FAReTek1** [comment]
yes probably

**Comment by FAReTek1** [comment]
(yes, pls merge 🥺)

**Comment by TheCommCraft** [comment]
> yeah i think so
> 

Sorry I didn't see the message

**Pull request merged**
