### PR TITLE
Use `warnings.warn` for displaying warnings

### PR DESCRIPTION
**Pull request by lemystic**
There were lines like these:
```py
print("Warning: ...")
``` 
sprinkled throughout some modules. There's no way to handle these print statements, so I replaced such `print` statements with `warnings.warn`. Using this function makes it possible to catch warnings like exceptions and suppress them as needed.

### CODE REVIEW

**Comment by Racecar-Roaster** [comment]
#70 
This can be used in a great way! Since as you said it would be like an emergency suppresser. Sorry if I sound like a random kid in a office I don't really go to pull requests often. Also what kind of stuff happening are needed for this to be triggered? How is it going to be like this with the `print` being replaced with a `warning.warn`

**Comment by lemystic** [comment]
> How is it going to be like this with the `print` being replaced with a `warning.warn`

Basically, all warnings are formatted like `Warning: message` where "Warning" is something like [`DeprecationWarning`](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) or [`UserWarning`](https://docs.python.org/3/library/exceptions.html#UserWarning) and "message" is the extra information.

You can ignore warnings by using this code in a program:
```py
import warnings
warnings.filterwarnings("ignore")
```

**Comment by Racecar-Roaster** [comment]
Really cool!

**Comment by TimMcCool** [comment]
Okay, will be added in the next update

**Comment by Racecar-Roaster** [comment]
Nice!

**Comment by TimMcCool** [comment]
Will be implemented in v1.1.8

**Pull request closed without merging**
