### PR TITLE
Update home.md

### PR DESCRIPTION
**Pull request by JackAttack365**
small addition

### CODE REVIEW

**Comment by TheCommCraft** [comment]
afaik this isn't specific to mac

**Comment by TimMcCool** [comment]
Hmm, on my device (Windows) `python -m pip` works but `python3 -m pip` doesn't

**Comment by TheCommCraft** [comment]
if you install python 2 and then 3 then it's python3

**Comment by JackAttack365** [comment]
Yes, and Mac comes with preinstalled python2

**Comment by TheCommCraft** [comment]
Well that's kinda dumb

Jack Shim ***@***.***> schrieb am So., 29. Sept. 2024, 16:29:

**Pull request merged**
